### PR TITLE
Add SPM and tvOS support

### PR DESCRIPTION
**Pull request by cntrump**

### CODE REVIEW

**Comment by cntrump** [comment]
Fixed https://github.com/tanhakabir/SwiftAudioPlayer/issues/85

**Comment by tanhakabir** [comment]
Hey! Thank you for the help! This PR is quite big though and seems to be doing a lot in one. If you're able to could you make separate PRs for the different changes? I'd checkout specific commits, create a branch, and PR from the multiple branches

**Comment by tanhakabir** [comment]
Why did you rename the Example app project?

**Comment by cntrump** [comment]
> Why did you rename the Example app project?

`Example/SwiftAudioPlayer.xcodeproj` is duplicate with `SwiftAudioPlayer.xcodeproj` at root.

>  If you're able to could you make separate PRs for the different changes?

Yeah, it is my mistake ... I will make separate PRs later.

**Pull request closed without merging**
