### PR TITLE
Fixed issue 99v2

### PR DESCRIPTION
**Pull request by krishjainx**
Changed to fix issue #99 "Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift " . Please review and merge @tanhakabir .

### CODE REVIEW

**Comment by Krish-sysadmin** [comment]
Bump @tanhakabir  ^

**Comment by cntrump** [comment]
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        
        SAPlayer.Downloader.allowUsingCellularData = true
        
//        SAPlayer.shared.DEBUG_MODE = true
        
        isPlayable = false
        checkIfAudioDownloaded()
        selectAudio(atIndex: 0)
        
//        addRandomModifiers()
        
        subscribeToChanges()
    }
```

Why comment `addRandomModifiers()` ?

**Comment by Krish-sysadmin** [comment]
@cntrump Sorry, just saw this. Yeah, it was human error. @tanhakabir Can you review it and merge it?

**Comment by tanhakabir** [comment]
@Krish-sysadmin I can't merge this in since it doesn't actually fix the issue :/ Your PR seems to add an additional reverb node and improve the reverb label but not actually fix the crash

**Review by tanhakabir — COMMENTED** [review]
Doesn't fix #99 sorry :(

**Comment by Krish-sysadmin** [comment]
@tanhakabir Well I can change the title since it does improve the reverb label and then it can be merged seperately?

**Comment by Krish-sysadmin** [comment]
By the way @tanhakabir  I emailed you, earlier could you have a look and please respond? Thanks :)

**Pull request closed without merging**
